openapi: 3.0.3
info:
  version: 1.0.0
  title: andalusianAPI
  description: api para informacion de bicicletas 

paths:
  /api/v1/bicicletas:
    x-router-controller: petsController
    get:
      description: Returns all bicicletas
      operationId: getBicicletas
      responses:
        200:
          description: Bicicleta list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/bicicleta'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    post:
      description: Creates a new bicicleta
      operationId: addBicicleta
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bicicleta'
        description: Bicicleta to be created
        required: true
      responses:
        201:
          description: Bicicleta
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  /api/v1/bicicletas/{year}:
    x-router-controller: petsController
    get:
      description: Returns a single bicicleta by its year
      operationId: findByyear
      parameters:
        - required: true
          name: year
          description: year of the bicicleta to fetch
          in: path
          schema:
            type: number
      responses:
        200:
          description: Bicicleta found by year
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bicicleta'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    put:
      description: Update a bicicleta based on its year
      operationId: updateBicicleta
      parameters:
        - required: true
          name: year
          description: year of the bicicleta to update
          in: path
          schema:
            type: number
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bicicleta'
        description: Bicicleta to be updated
        required: true
      responses:
        204:
          description: Bicicleta updated
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    delete:
      description: Deletes a single bicicleta based on its year
      operationId: deleteBicicleta
      parameters:
        - required: true
          name: year
          description: year of the bicicleta to delete
          in: path
          schema:
            type: number
      responses:
        204:
          description: Bicicleta deleted
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

components:
  schemas:
    bicicleta:
        type: object
        required:
          - year
        properties:
          province:
            type: string
          population:
            type: number
          walking:
            type: number
          bicycle:
            type: number
          year:
            type: number
          motorized_percentage:
            type: number
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
      additionalProperties: true